championship/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.championships, name="championships"),
    path("categorys/", views.categorys, name="categorys"),
    path("create_category/", views.create_category, name="create_category"),
    path(
        "delete_championship/<int:id>/",
        views.delete_championship,
        name="delete_championship",
    ),
    path("teams/", views.teams, name="teams"),
    path("create_team/", views.create_team, name="create_team"),
    # path("delete_team1/<int:id>/<int:id_champ>/", views.delete_team, name="delete_team"),

    path("create_fixture/<int:championship_id>/<int:category_id>/", views.create_fixture, name="create_fixture"),
    path("game/<int:game_id>/", views.game, name="game"),
    path('game_status/<int:game_id>/', views.game_status, name='game_status'),


    path("delete_team/<int:id>/<int:id_champ>/", views.delete_team, name="delete_team"),
    # path('add_player_team/<int:player_id>/', views.add__player_team, name='add_player_team'),
    path("view_team/<int:team_id>/", views.view_team, name="view_team"),
    path("persons/", views.persons, name="persons"),  # Person
    path("create_person/", views.create_person, name="create_person"),  # Person
    path(
        "edit_person/<int:person_id>/", views.edit_person, name="edit_person"
    ),  # Person
    path(
        "view_person/<int:person_id>/", views.view_person, name="view_person"
    ),  # Person
    path(
        "delete_person/<int:person_id>/", views.delete_person, name="delete_person"
    ),  # Person
    #path("add_team_championship/<int:championship_id>/",views.add_team_championship,name="add_team_championship",),
    # path('view1_championship/<int:championship_id>/', views.view1_championship, name='view1_championship'),
    path("create_championship/", views.create_championship, name="create_championship"),
    path(
        "remove_player_from_team/<int:team_id>/<int:player_id>/",
        views.remove_player_from_team,
        name="remove_player_from_team",
    ),
    path("delete_team/<int:team_id>/", views.delete_team, name="delete_team"),
    path(
        "remove_team_from_championship/<int:championship_id>/<int:category_id>/<int:team_id>/",
        views.remove_team_from_championship,
        name="remove_team_from_championship",
    ),
    path(
        "delete_category/<int:category_id>/",
        views.delete_category,
        name="delete_category",
    ),
    path("edit_category/<int:category_id>/", views.edit_category, name="edit_category"),
    path(
        "edit_championship/<int:championship_id>",
        views.edit_championship,
        name="edit_championship",
    ),
    path("edit_team/<int:team_id>", views.edit_team, name="edit_team"),
    path("view_championship/<int:championship_id>", views.view_championship, name="view_championship"),
    path("add_team_championship/<int:championship_id>/<int:categorys_id>/",views.add_team_championship,name="add_team_championship"),
    #--Creacion de los nuevos modelos disciplina
    path("disciplines/", views.disciplines, name="disciplines"),
    path("create_discipline/", views.create_discipline, name="create_discipline"),
    path("delete_discipline/<int:discipline_id>/",views.delete_discipline,name="delete_discipline",),
    path("edit_discipline/<int:discipline_id>/", views.edit_discipline, name="edit_discipline"),
    #--Creacopm del modelo temporada
    path("seasons/", views.seasons, name="seasons"),
    path("create_season/", views.create_season, name="create_season"),
    path("delete_season/<int:season_id>/",views.delete_season,name="delete_season",),
    path("edit_season/<int:season_id>/", views.edit_season, name="edit_season"),
    #--Actualizacion de la persona marcada como delegado del equipo
    path('actualizar_jugador/<int:player_id>/', views.actualizar_jugador, name='actualizar_jugador'),
    path('actualizar_jugador1/<int:player_id>/', views.actualizar_jugador1, name='actualizar_jugador1'),

    path('tabla_posiciones/<int:championship_id>/<int:category_id>/', views.tabla_posiciones, name='tabla_posiciones'),
    path('amonestaciones/<int:championship_id>/<int:category_id>/', views.amonestaciones, name='amonestaciones'),
    path('goleadores/<int:championship_id>/<int:category_id>/', views.goleadores, name='goleadores'),

    # Modulo anuncios
    path('anuncios/', views.anuncios,  name='anuncios'),
    path('denied/', views.denied,  name='denied'),

    path('create_anuncio/', views.create_anuncio,  name='create_anuncio'),
    path('delete_anuncio/<int:anuncio_id>', views.delete_anuncio,  name='delete_anuncio'),
    path('edit_anuncio/<int:anuncio_id>', views.edit_anuncio,  name='edit_anuncio'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("partner.urls")),
    path("championship/", include("championship.urls")),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

championship/models.py
from django.db import models
from .validators import validate_str, validate_dni, validate_phone, validate_month, validate_year
from django.core.validators import MaxValueValidator
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils import timezone
import pytz

person_department = [
    (1, 'Amazonas'),
    (2, 'Ancash'),
    (3, 'Apurimac'),
    (4, 'Arequipa'),
    (5, 'Ayacucho'),
    (6, 'Cajamarca'),
    (7, 'Callao'),
    (8, 'Cusco'),
    (9, 'Huancavelica'),
    (10, 'Huanuco'),
    (11, 'Ica'),
    (12, 'Junín'),
    (13, 'La Libertad'),
    (14, 'Lambayeque'),
    (15, 'Lima'),
    (16, 'Loreto'),
    (17, 'Madre de Dios'),
    (18, 'Moquegua'),
    (19, 'Pasco'),
    (20, 'Piura'),
    (21, 'Puno'),
    (22, 'San Martín'),
    (23, 'Tacna'),
    (24, 'Tumbes'),
    (25, 'Ucayali'),
]


BOOLEAN_CHOICES = [
    (False, 'No'),
    (True, 'Si'),
]


class Person(models.Model):
    name = models.CharField(max_length=30, validators=[validate_str])
    surnames = models.CharField(max_length=30, validators=[validate_str])
    dni = models.PositiveIntegerField(unique=True, validators=[validate_dni])
    date_created = models.DateTimeField(auto_now_add=True)
    birthdate = models.DateField(blank=True, null=True)
    department = models.IntegerField(
        null=False, blank=False,
        choices=person_department,
        default=4)
    province = models.CharField(blank=True, max_length=30)
    district = models.CharField(blank=True, max_length=30)
    address = models.CharField(blank=True, max_length=50)
    profession = models.CharField(
        max_length=30, blank=True, validators=[validate_str])
    activity = models.CharField(
        max_length=30, blank=True, validators=[validate_str])
    degree_instruction = models.CharField(
        max_length=30, blank=True, validators=[validate_str])
    civil_status = models.CharField(
        max_length=50, blank=True, validators=[validate_str])
    military_card = models.PositiveIntegerField(
        unique=True, blank=True, null=True, validators=[validate_phone])
    phone = models.PositiveIntegerField(
        blank=True, null=True, validators=[validate_phone])
    promotion_delegate = models.BooleanField(
        choices=BOOLEAN_CHOICES, default=False)
    promotion_sub_delegate = models.BooleanField(
        choices=BOOLEAN_CHOICES, default=False)
    partner = models.BooleanField(
        choices=BOOLEAN_CHOICES, default=False)
    image = models.ImageField(upload_to='pics', blank=True, null=True)
    NSA_code = models.CharField(max_length=100, blank=True, null=True)
    month_promotion = models.CharField(
        max_length=15, validators=[validate_month])
    year_promotion = models.PositiveIntegerField(validators=[validate_year])
    is_jale = models.BooleanField(default=False)
    # Agregamos el campo team_delagate
    team_delegate = models.BooleanField(
        choices=BOOLEAN_CHOICES, default=False)

    def __str__(self):
        return self.name
# -----------------------------


class Team(models.Model):
    name = models.CharField(max_length=50)
    month = models.CharField(max_length=100, validators=[validate_month])
    year = models.PositiveIntegerField(validators=[validate_year])
    group = models.CharField(max_length=5)
    state = models.BooleanField(choices=BOOLEAN_CHOICES, default=True)
    persons = models.ManyToManyField(Person)

    def __str__(self):
        return self.month


class Category(models.Model):
    name = models.PositiveIntegerField()

    def __str__(self):
        return str(self.name)

# --Creacion del modelo diciplina


class Discipline(models.Model):
    name = models.CharField(max_length=30, validators=[validate_str])

    def __str__(self):
        return self.name

# --Creacion del modelo temporada


class Season(models.Model):
    name = models.CharField(max_length=30, validators=[validate_str])

    def __str__(self):
        return self.name


class Championship(models.Model):
    name = models.CharField(max_length=20, validators=[validate_str])
    year = models.PositiveIntegerField(validators=[validate_year])
    # --Agregamos los nuevos modelos creados como campos para la creacion de un campeonato
    disciplines = models.ForeignKey(Discipline, on_delete=models.CASCADE)
    seasons = models.ForeignKey(Season, on_delete=models.CASCADE)
    # ----------------------------------------------------------------
    rule = models.TextField(blank=True, null=True)
    categorys = models.ManyToManyField(Category)
    state = models.BooleanField(choices=BOOLEAN_CHOICES, default=True)
    # date_created = models.DateTimeField(auto_now_add=True)
    # date_finished = models.DateTimeField(null=True, blank=True)
    teams = models.ManyToManyField(Team, through='ChampionshipTeam')

    def __str__(self):
        return self.name


class ChampionshipTeam(models.Model):
    championship = models.ForeignKey(Championship, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.championship.name} - {self.category.name} - {self.team.month}"


class Anuncio(models.Model):
    name = models.CharField(max_length=30)
    content = models.TextField(blank=True, null=True)
    date = models.DateField(null=True, blank=True)
    time = models.TimeField(null=True, blank=True)
    championship = models.ForeignKey(Championship, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Game(models.Model):
    round_number = models.PositiveIntegerField(default=0)
    championship = models.ForeignKey(Championship, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    team1 = models.ForeignKey(
        Team, related_name='team1', on_delete=models.CASCADE)
    team2 = models.ForeignKey(
        Team, related_name='team2', on_delete=models.CASCADE)
    # date = models.DateTimeField(null=True, blank=True)
    team1_goals = models.PositiveIntegerField(
        default=0, validators=[MaxValueValidator(limit_value=30)])
    team2_goals = models.PositiveBigIntegerField(
        default=0, validators=[MaxValueValidator(limit_value=30)])
    # state = models.BooleanField(default=True)
    players = models.ManyToManyField(Person, through="PlayerGame")
    state = models.BooleanField(default=False)
    sum_team_points = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "Fecha: " + str(self.round_number) + ". " + self.team1.month + " " + str(self.team1_goals) + "-" + str(self.team2_goals) + " " + self.team2.month + " | "

# -----------------------------------


class PlayerGame(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    player = models.ForeignKey(Person, on_delete=models.CASCADE)
    card_red = models.PositiveIntegerField(
        validators=[MaxValueValidator(limit_value=1)], default=0)
    card_yellow = models.PositiveIntegerField(
        validators=[MaxValueValidator(limit_value=2)], default=0)
    goals = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        # Verifica si card_yellow igual a 2
        if self.card_yellow == 2:
            # Si es igual a 2, establece card_red en 1
            self.card_red = 1

        super().save(*args, **kwargs)


class Result(models.Model):
    round_number = models.PositiveIntegerField(default=0)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    championship = models.ForeignKey(Championship, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    pj = models.IntegerField(default=0)
    pg = models.IntegerField(default=0)
    pe = models.IntegerField(default=0)
    pp = models.IntegerField(default=0)
    gf = models.IntegerField(default=0)
    gc = models.IntegerField(default=0)
    # diferencia de goles a favor y en contra
    dg = models.IntegerField(default=0)
    pts = models.IntegerField(default=0)


# --funcion para actualizar la hor ay fecha
# Definir una función para manejar la señal
@receiver(pre_save, sender=Anuncio)
def set_default_date_time(sender, instance, **kwargs):
    # Obtener la zona horaria de Perú
    peru_tz = pytz.timezone('America/Lima')

    # Verificar si date y time están en blanco
    if instance.date is None:
        # Asignar la fecha actual en la zona horaria de Perú
        instance.date = timezone.now().astimezone(peru_tz).date()

    if instance.time is None:
        # Asignar la hora actual en la zona horaria de Perú
        instance.time = timezone.now().astimezone(peru_tz).strftime('%H:%M:%S')


# Conectar la función a la señal
pre_save.connect(set_default_date_time, sender=Anuncio)

templates/championship/anuncio/create_anuncio.html
{% extends 'layout/main.html' %}
{% block content %}
<div class="mt-4 mb-4">
  <div class="col-md-6 offset-md-3">
    <form method="POST">
      <h1 style="
          font-family: 'Montserrat';
          font-size: 50px;
          color: #0E172D;
          border-bottom: 1.5px solid #babfc5;
          padding-bottom: 15px;
        ">
        Crear anuncio
      </h1>
      <a
        class="btn mt-4 mb-2 fs-5"
        role="button"
        href="{% url 'anuncios' %}"
        style="
          background-color: #242C43;
          font-family: 'Montserrat';
          box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
          transition: background-color 0.3s;
          color: white;
        "
        onmouseover="this.style.backgroundColor='#090C26'"
            onmouseout="this.style.backgroundColor='#242C43'"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="25"
          height="25"
          fill="white"
          class="bi bi-arrow-left"
          viewBox="0 0 16 16"
        >
          <path
            fill-rule="evenodd"
            d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"
          />
        </svg>
        Volver a anuncios
      </a>
      <div style="background-color: white; padding: 15px; border-radius: 15px; margin-bottom: 15px; margin-top: 20px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);">
        <div class="mb-3">
          <!-- <label style="
              color: black;
              font-family: 'Montserrat';
              font-size: 20px;
              font-weight: normal;
              display: block;
              margin-bottom: 5px; /* Agregamos margen inferior */
            ">Publicar ahora:</label> -->
          <div style="display: flex; align-items: center;">
            <span style="margin-right: 10px;">{{ form.default }}</span>
            <span style="font-size: 20px; font-family: 'Montserrat'; color: black;">Publicar ahora</span>
          </div>
        </div>
        <div class="mb-3">
          <!-- <label style="
              color: black;
              font-family: 'Montserrat';
              font-size: 20px;
              font-weight: normal;
              display: block;
              margin-bottom: 5px; /* Agregamos margen inferior */
            ">Programar:</label> -->
          <div style="display: flex; align-items: center;">
            <span style="margin-right: 10px;">{{ form.programar }}</span>
            <span style="font-size: 20px; font-family: 'Montserrat'; color: black;">Programar</span>
          </div>
        </div>
        <div style="display: flex; align-items: center; margin-left: 25px; margin-right: 25px;" class="mb-3">
          <div style="flex: 1; margin-right: 10px;">
            <label style="
                color: black;
                font-family: 'Montserrat';
                font-size: 20px;
                font-weight: normal;
              " for="id_date">Fecha:</label>
            {{ form.date }}
          </div>
          <div style="flex: 1; margin-left: 10px;">
            <label style="
                color: black;
                font-family: 'Montserrat';
                font-size: 20px;
                font-weight: normal;
              " for="id_time">Hora:</label>
            {{ form.time }}
          </div>
        </div>
      </div>

      <div class="mb-3">
        <label style="
            color: black;
            font-family: 'Montserrat';
            font-size: 20px;
            font-weight: normal;
          " for="id_championship">Campeonato:</label>
        {{ form.championship }}
      </div>
      <div class="mb-3">
        <label style="
            color: black;
            font-family: 'Montserrat';
            font-size: 20px;
            font-weight: normal;
          " for="id_name">Título:</label>
        {{ form.name }}
      </div>
      <div class="mb-3">
        <label style="
            color: black;
            font-family: 'Montserrat';
            font-size: 20px;
            font-weight: normal;
          " for="id_content">Descripción:</label>
        {{ form.content }}
      </div>
      {% csrf_token %}
      <div class="d-grid gap-2 d-md-flex justify-content-md-center">
        <button class="btn mt-4 mb-2 w-100 fs-5" style="
            background-color: #242C43;
            font-family: 'Montserrat';
            box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
            transition: background-color 0.3s;
            color: white;
          " onmouseover="this.style.backgroundColor='#090C26'"
            onmouseout="this.style.backgroundColor='#242C43'">
          Crear anuncio
        </button>
      </div>
    </form>
  </div>
</div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const programarCheckbox = document.getElementById('id_programar');
    const dateInput = document.getElementById('id_date');
    const timeInput = document.getElementById('id_time');
    const defaultCheckbox = document.getElementById('id_default');
    const dateLabel = document.querySelector('[for="id_date"]');
    const timeLabel = document.querySelector('[for="id_time"]');
    
    function toggleDateTimeFields() {
      if (programarCheckbox.checked) {
        dateInput.removeAttribute('disabled');
        timeInput.removeAttribute('disabled');
        dateLabel.classList.remove('disabled-field');
        timeLabel.classList.remove('disabled-field');
        defaultCheckbox.checked = false;
      } else {
        dateInput.setAttribute('disabled', 'true');
        timeInput.setAttribute('disabled', 'true');
        dateLabel.classList.add('disabled-field');
        timeLabel.classList.add('disabled-field');
        defaultCheckbox.checked = true;
      }
    }
    
    function toggleDefaultCheckbox() {
      if (defaultCheckbox.checked) {
        programarCheckbox.checked = false;
        dateInput.setAttribute('disabled', 'true');
        timeInput.setAttribute('disabled', 'true');
        dateLabel.classList.add('disabled-field');
        timeLabel.classList.add('disabled-field');
      } else {
        programarCheckbox.checked = true;
        dateInput.removeAttribute('disabled');
        timeInput.removeAttribute('disabled');
        dateLabel.classList.remove('disabled-field');
        timeLabel.classList.remove('disabled-field');
      }
    }
    
    toggleDateTimeFields();
    programarCheckbox.addEventListener('change', toggleDateTimeFields);
    defaultCheckbox.addEventListener('change', toggleDefaultCheckbox);
  });
</script>
<style>
  .disabled-field {
    color: #aaa; /* Color gris para el texto */
    pointer-events: none; /* Evita la interacción con el campo */
    opacity: 0.6; /* Opacidad del campo */
  }
</style>
{% endblock content %}

templates/championship/anuncio/denied.html
{% extends 'layout/main.html' %} {% block content %}{% load static %}

<div class="container text-center">
  <img
    src="{% static 'img/ad.png' %}"
    alt="Imagen de acceso no permitido"
    class="img-fluid"
  />
</div>
{% endblock content %}

templates/championship/anuncio/edit_anuncio.html
{% extends 'layout/main.html' %}
{% block content %}
<div class="mt-4 mb-4">
  <div class="col-md-6 offset-md-3">
    <form method="POST">
      <h1 style="
          font-family: 'Montserrat';
          font-size: 50px;
          color: #0E172D;
          border-bottom: 1.5px solid #babfc5;
          padding-bottom: 15px;
        ">
        Editar anuncio
      </h1>
      <a
        class="btn mt-4 mb-2 fs-5"
        role="button"
        href="{% url 'anuncios' %}"
        style="
          background-color: #242C43;
          font-family: 'Montserrat';
          box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
          transition: background-color 0.3s;
          color: white;
        "
       onmouseover="this.style.backgroundColor='#090C26'"
            onmouseout="this.style.backgroundColor='#242C43'"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="25"
          height="25"
          fill="white"
          class="bi bi-arrow-left"
          viewBox="0 0 16 16"
        >
          <path
            fill-rule="evenodd"
            d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"
          />
        </svg>
        Volver a anuncios
      </a>
      <div style="background-color: white; padding: 15px; border-radius: 15px; margin-bottom: 15px; margin-top: 20px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);">
        <div class="mb-3">
          <!-- <label style="
              color: black;
              font-family: 'Montserrat';
              font-size: 20px;
              font-weight: normal;
              display: block;
              margin-bottom: 5px; /* Agregamos margen inferior */
            ">Publicar ahora:</label> -->
          <div style="display: flex; align-items: center;">
            <span style="margin-right: 10px;">{{ form.default }}</span>
            <span style="font-size: 20px; font-family: 'Montserrat'; color: black;">Publicar ahora</span>
          </div>
        </div>
        <div class="mb-3">
          <!-- <label style="
              color: black;
              font-family: 'Montserrat';
              font-size: 20px;
              font-weight: normal;
              display: block;
              margin-bottom: 5px; /* Agregamos margen inferior */
            ">Programar:</label> -->
          <div style="display: flex; align-items: center;">
            <span style="margin-right: 10px;">{{ form.programar }}</span>
            <span style="font-size: 20px; font-family: 'Montserrat'; color: black;">Programar</span>
          </div>
        </div>
        <div style="display: flex; align-items: center; margin-left: 25px; margin-right: 25px;" class="mb-3">
          <div style="flex: 1; margin-right: 10px;">
            <label style="
                color: black;
                font-family: 'Montserrat';
                font-size: 20px;
                font-weight: normal;
              " for="id_date">Fecha:</label>
            {{ form.date }}
          </div>
          <div style="flex: 1; margin-left: 10px;">
            <label style="
                color: black;
                font-family: 'Montserrat';
                font-size: 20px;
                font-weight: normal;
              " for="id_time">Hora:</label>
            {{ form.time }}
          </div>
        </div>
      </div>

      <div class="mb-3">
        <label style="
            color: black;
            font-family: 'Montserrat';
            font-size: 20px;
            font-weight: normal;
          " for="id_championship">Campeonato:</label>
        {{ form.championship }}
      </div>
      <div class="mb-3">
        <label style="
            color: black;
            font-family: 'Montserrat';
            font-size: 20px;
            font-weight: normal;
          " for="id_name">Título:</label>
        {{ form.name }}
      </div>
      <div class="mb-3">
        <label style="
            color: black;
            font-family: 'Montserrat';
            font-size: 20px;
            font-weight: normal;
          " for="id_content">Descripción:</label>
        {{ form.content }}
      </div>
      {% csrf_token %}
      <div class="d-grid gap-2 d-md-flex justify-content-md-center">
        <button class="btn mt-4 mb-2 w-100 fs-5" style="
            background-color:#242C43;
            font-family: 'Montserrat';
            box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
            transition: background-color 0.3s;
            color: white;
          " onmouseover="this.style.backgroundColor='#090C26'"
            onmouseout="this.style.backgroundColor='#242C43'">
          Editar anuncio
        </button>
      </div>
    </form>
  </div>
</div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const programarCheckbox = document.getElementById('id_programar');
    const dateInput = document.getElementById('id_date');
    const timeInput = document.getElementById('id_time');
    const defaultCheckbox = document.getElementById('id_default');
    const dateLabel = document.querySelector('[for="id_date"]');
    const timeLabel = document.querySelector('[for="id_time"]');
    
    function toggleDateTimeFields() {
      if (programarCheckbox.checked) {
        dateInput.removeAttribute('disabled');
        timeInput.removeAttribute('disabled');
        dateLabel.classList.remove('disabled-field');
        timeLabel.classList.remove('disabled-field');
        defaultCheckbox.checked = false;
      } else {
        dateInput.setAttribute('disabled', 'true');
        timeInput.setAttribute('disabled', 'true');
        dateLabel.classList.add('disabled-field');
        timeLabel.classList.add('disabled-field');
        defaultCheckbox.checked = true;
      }
    }
    
    function toggleDefaultCheckbox() {
      if (defaultCheckbox.checked) {
        programarCheckbox.checked = false;
        dateInput.setAttribute('disabled', 'true');
        timeInput.setAttribute('disabled', 'true');
        dateLabel.classList.add('disabled-field');
        timeLabel.classList.add('disabled-field');
      } else {
        programarCheckbox.checked = true;
        dateInput.removeAttribute('disabled');
        timeInput.removeAttribute('disabled');
        dateLabel.classList.remove('disabled-field');
        timeLabel.classList.remove('disabled-field');
      }
    }
    
    toggleDateTimeFields();
    programarCheckbox.addEventListener('change', toggleDateTimeFields);
    defaultCheckbox.addEventListener('change', toggleDefaultCheckbox);
  });
</script>
<style>
  .disabled-field {
    color: #aaa; /* Color gris para el texto */
    pointer-events: none; /* Evita la interacción con el campo */
    opacity: 0.6; /* Opacidad del campo */
  }
</style>
{% endblock content %}